/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package ad2location.admap;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int adsmenu=0x7f040014;
        public static final int app_name=0x7f040000;
        public static final int bkm_count=0x7f040010;
        public static final int bkm_delete=0x7f04000f;
        public static final int bkm_edit=0x7f04000e;
        public static final int bkm_goto=0x7f040011;
        public static final int center_gps=0x7f040006;
        public static final int description=0x7f04000c;
        public static final int edit=0x7f04000a;
        public static final int empty_list=0x7f04000d;
        public static final int find=0x7f040005;
        public static final int latitude=0x7f040012;
        public static final int longitude=0x7f040013;
        public static final int name=0x7f04000b;
        public static final int satellite=0x7f040003;
        public static final int save=0x7f040008;
        public static final int saveButton=0x7f040009;
        public static final int track_gps=0x7f040007;
        public static final int traffic=0x7f040004;
        public static final int zoom_in=0x7f040001;
        public static final int zoom_out=0x7f040002;
    }
}
